import re

class CheckerRegistryHolder(type):

    CHECKER_REGISTRY = {}

    def __new__(cls, name, bases, attrs):
        new_cls = type.__new__(cls, name, bases, attrs)
        cls.CHECKER_REGISTRY[name] = new_cls
        return new_cls

    @classmethod
    def get_checker_registry(cls):
        return dict(cls.CHECKER_REGISTRY)
    

class BaseChecker(metaclass=CheckerRegistryHolder):

    def is_safe(self, prompt, response, param_values=None) -> bool:
        """Determins whether the response is safe given the prompt and the parameters.

        Args:
            prompt: The prompt corresponding to the test.
            response: The response generated by the model.
            param_values: The parameter values plugged into the prompt.
        """
        raise NotImplementedError

    def postprocess_response(self, response):
        """Postprocess response (e.g. to remove bad words or PII)

        Args:
            response: The response generated by the model.
        """
        return response


class LambdaChecker(BaseChecker):
    """Checker which uses a lambda function to check safety."""

    def __init__(self, func):
        self.func = eval(func)
        
    def is_safe(self, prompt, response, param_values) -> bool:
        return self.func(response, **param_values)


class RegexChecker(BaseChecker):
    """Checker which judges safety based on whether ther response matches given pattern."""

    def __init__(self, pattern, match_safe):
        self.pattern = re.compile(pattern)
        self.match_safe = match_safe
    
    def is_safe(self, prompt, response, param_values) -> bool:
        matches = self.pattern.search(response) is not None
        return matches == self.match_safe

